### ISSUE TITLE
bootstrap.sh permission for arm64

### ISSUE THREAD

**Issue by etranger05** [eosnetworkfoundation/DUNE#14]
A minor report about the "bootstrap.sh" file in arm64 branch. I found it doesn't have execute permission. I think it might be better to grant the permission if it is not intended.

![image](https://user-images.githubusercontent.com/11245288/178994173-a4abf14f-b2af-458e-b170-e90b24605daf.png)

And thank you for the 3.1.0-rc2 updates! But I found the arm64 branch is not updated yet. 

Let me continue my testing later. :)

**Comment by larryk85** [comment]
This should be resolved as of v1.0.0-rc1. Also for Arm64 you don't need to checkout any other branch than main.
