### ISSUE TITLE
Bootstrapping phase fails on Windows 10

### ISSUE THREAD

**Issue by vladtr** [eosnetworkfoundation/DUNE#24]
While troubleshooting issue #21 and testing scripts on Windows it appears that bootstrap step of setting up the environment errors out.

=> [ 2/19] RUN apt-get update                                                                                    16.9s
=> [ 3/19] RUN apt-get update --fix-missing                                                                       1.8s
=> [ 4/19] RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata                                2.8s
=> [ 5/19] RUN apt-get -y install zip unzip libncurses5 wget git build-essential cmake curl libboost-all-dev l  318.6s
=> [ 6/19] RUN npm install -D webpack-cli                                                                         5.6s
=> [ 7/19] RUN npm install -D webpack                                                                            11.5s
=> [ 8/19] RUN npm install -D webpack-dev-server                                                                 18.1s
=> [ 9/19] WORKDIR /app                                                                                           0.0s
=> [10/19] COPY ./scripts/ .                                                                                      0.0s
=> [11/19] RUN chmod +x bootstrap_env.sh                                                                          0.4s
=> [12/19] RUN chmod +x start_node.sh                                                                             0.5s
=> [13/19] RUN chmod +x setup_system.sh                                                                           0.5s
=> [14/19] RUN chmod +x write_context.sh                                                                          0.6s
=> [15/19] RUN mv my_init /sbin                                                                                   0.5s
=> [16/19] RUN ./bootstrap_env.sh                                                                               102.1s
=> [17/19] RUN ./setup_system.sh                                                                                  0.5s
=> ERROR [18/19] RUN mkdir /home/www-data/nodes                                                                   0.6s
[18/19] RUN mkdir /home/www-data/nodes:
#26 0.572 mkdir: cannot create directory '/home/www-data/nodes': No such file or directory
executor failed running [/bin/sh -c mkdir /home/www-data/nodes]: exit code: 1

**Setup**: 

- Win10, freshly installed with all the updates, no extra software
- Installed Docker Desktop per instructions
- Installed Python3 per instructions
- added dune to path and run bootstrap.bat, it runs for 10+ minutes and errors out

Here is one caveat - for some reason, if you install python from the Python website and add it to path, dune has trouble finding it:

Microsoft Windows [Version 10.0.19044.1889]
(c) Microsoft Corporation. All rights reserved.

C:\Users\valter>dune
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

C:\Users\valter>python
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by arhag** [comment]
Resolved by https://github.com/AntelopeIO/DUNE/pull/4.

**Comment by larryk85** [comment]
Resolved as part of https://github.com/AntelopeIO/DUNE/pull/4.
