### ISSUE TITLE
WASM runtime is not supported

### ISSUE THREAD

**Issue by etranger05** [eosnetworkfoundation/DUNE#8]
In my environment, docker is running on M1 Mac and did checkout DUNE 'arm64' branch
-----------------------------------
```
$ dune --start test_node
:
:
warn  2022-07-08T12:58:06.514 nodeos    chain_plugin.cpp:1238         plugin_initialize    ] 3070000 wasm_exception: WASM Exception
eos_vm_jit wasm runtime not supported on this platform and/or configuration
    {"r":"eos_vm_jit"}
    nodeos  wasm_interface_private.hpp:79 wasm_interface_impl

error 2022-07-08T12:58:06.514 nodeos    main.cpp:150                  main                 ] 3070000 wasm_exception: WASM Exception
eos_vm_jit wasm runtime not supported on this platform and/or configuration
    {"r":"eos_vm_jit"}
    nodeos  wasm_interface_private.hpp:79 wasm_interface_impl
rethrow
    {}
    nodeos  chain_plugin.cpp:1238 plugin_initialize
```
----------------------------------

Is "eos_vm_jit" supporting the arm64 platform?
Any idea how to solve this error?

**Comment by ericpassmore** [comment]
Do you have wasm runtime installed? Only a suggestion as I don't have a m1 to validate
https://docs.wasmer.io/ecosystem/wasmer/getting-started
https://formulae.brew.sh/formula/wasmer

**Comment by ericpassmore** [comment]
ah eos_vm_jit is a wasm runtime. My mistake. You can try changing DUNE/script/config.ini  to _eos-vm_ or _eos-vm-oc_ Some documentation under [mandel chain_plugin](https://github.com/eosnetworkfoundation/mandel/blob/main/docs/01_nodeos/03_plugins/chain_plugin/index.md)

**Comment by etranger05** [comment]
> ah eos_vm_jit is a wasm runtime. My mistake. You can try changing DUNE/script/config.ini to _eos-vm_ or _eos-vm-oc_ Some documentation under [mandel chain_plugin](https://github.com/eosnetworkfoundation/mandel/blob/main/docs/01_nodeos/03_plugins/chain_plugin/index.md)

I set up wasm-runtime = eos-vm and found the node works. Thank you!

**Comment by ericpassmore** [comment]
Thanks which file did you change? I want to patch this so it doesn't happen again.

**Comment by etranger05** [comment]
> Thanks which file did you change? I want to patch this so it doesn't happen again.

DUNE/script/config.ini, as you commented. Changed it before run bootstrap.sh

**Comment by ericpassmore** [comment]
Thanks patch is here, please test if you have a moment. 
git clone -b mac_m1_wasm_runtime https://github.com/ericpassmore/macos-fixes.git
