### ISSUE TITLE
Node not starting on MacOS (M1)

### ISSUE THREAD

**Issue by RalfWeinand** [eosnetworkfoundation/DUNE#9]
Hello,

I've cloned dune (using latest MacOS on M1), changed to **arm64** branch and build DUNE based on that branch.

When starting up a node I get below error.
Please note that I have taken the confi.ini from the DUNE repository and have tried with 3 different values for the runtime: wabt, eos_vm_jit, and eos_vm.

However despite below log output stating that it is using my config file, it seems to ignore the runtime setting as I always get the same error, no matter if I use wabt, eos_vm_jit, or eos_vm.

---
./dune --start 'ralf' ./config.ini
Creating docker container [dune_container]
Creating node [ralf]

Using Configuration [/host//Users/ralfweinand/dev/DUNE/config.ini]

Active [ralf]

info  2022-07-09T07:47:04.092 nodeos    chain_plugin.cpp:658          plugin_initialize    ] initializing chain plugin
info  2022-07-09T07:47:04.093 nodeos    chain_plugin.cpp:462          operator()           ] Support for builtin protocol feature 'GET_CODE_HASH' (with digest of '960f851f3e2e96acf5bb2c79ac0522a7552c721b6e88a63a24bcf27970d620c5') is enabled with preactivation required
info  2022-07-09T07:47:04.093 nodeos    chain_plugin.cpp:571          operator()           ] Saved default specification for builtin protocol feature 'GET_CODE_HASH' (with digest of '960f851f3e2e96acf5bb2c79ac0522a7552c721b6e88a63a24bcf27970d620c5') to: /app/nodes/ralf/protocol_features/BUILTIN-GET_CODE_HASH.json
info  2022-07-09T07:47:04.093 nodeos    chain_plugin.cpp:462          operator()           ] Support for builtin protocol feature 'BLOCKCHAIN_PARAMETERS' (with digest of '8e466518f3e16a679ffa80d2e810e4097e89b0495ed70c112375a1f525093f33') is enabled with preactivation required
info  2022-07-09T07:47:04.094 nodeos    chain_plugin.cpp:571          operator()           ] Saved default specification for builtin protocol feature 'BLOCKCHAIN_PARAMETERS' (with digest of '8e466518f3e16a679ffa80d2e810e4097e89b0495ed70c112375a1f525093f33') to: /app/nodes/ralf/protocol_features/BUILTIN-BLOCKCHAIN_PARAMETERS.json
info  2022-07-09T07:47:04.094 nodeos    chain_plugin.cpp:462          operator()           ] Support for builtin protocol feature 'CONFIGURABLE_WASM_LIMITS2' (with digest of '29a255f3e311c053847e027d352c06c77dfa9648fd8fd5dc8f629e3efffc2109') is enabled with preactivation required
info  2022-07-09T07:47:04.097 nodeos    chain_plugin.cpp:571          operator()           ] Saved default specification for builtin protocol feature 'CONFIGURABLE_WASM_LIMITS2' (with digest of '29a255f3e311c053847e027d352c06c77dfa9648fd8fd5dc8f629e3efffc2109') to: /app/nodes/ralf/protocol_features/BUILTIN-CONFIGURABLE_WASM_LIMITS2.json
info  2022-07-09T07:47:04.097 nodeos    chain_plugin.cpp:462          operator()           ] Support for builtin protocol feature 'ACTION_RETURN_VALUE' (with digest of 'c3a6138c5061cf291310887c0b5c71fcaffeab90d5deb50d3b9e687cead45071') is enabled with preactivation required
info  2022-07-09T07:47:04.097 nodeos    chain_plugin.cpp:571          operator()           ] Saved default specification for builtin protocol feature 'ACTION_RETURN_VALUE' (with digest of 'c3a6138c5061cf291310887c0b5c71fcaffeab90d5deb50d3b9e687cead45071') to: /app/nodes/ralf/protocol_features/BUILTIN-ACTION_RETURN_VALUE.json
info  2022-07-09T07:47:04.097 nodeos    chain_plugin.cpp:462          operator()           ] Support for builtin protocol feature 'WTMSIG_BLOCK_SIGNATURES' (with digest of '299dcb6af692324b899b39f16d5a530a33062804e41f09dc97e9f156b4476707') is enabled with preactivation required
info  2022-07-09T07:47:04.097 nodeos    chain_plugin.cpp:571          operator()           ] Saved default specification for builtin protocol feature 'WTMSIG_BLOCK_SIGNATURES' (with digest of '299dcb6af692324b899b39f16d5a530a33062804e41f09dc97e9f156b4476707') to: /app/nodes/ralf/protocol_features/BUILTIN-WTMSIG_BLOCK_SIGNATURES.json
info  2022-07-09T07:47:04.097 nodeos    chain_plugin.cpp:462          operator()           ] Support for builtin protocol feature 'WEBAUTHN_KEY' (with digest of '4fca8bd82bbd181e714e283f83e1b45d95ca5af40fb89ad3977b653c448f78c2') is enabled with preactivation required
info  2022-07-09T07:47:04.098 nodeos    chain_plugin.cpp:571          operator()           ] Saved default specification for builtin protocol feature 'WEBAUTHN_KEY' (with digest of '4fca8bd82bbd181e714e283f83e1b45d95ca5af40fb89ad3977b653c448f78c2') to: /app/nodes/ralf/protocol_features/BUILTIN-WEBAUTHN_KEY.json
info  2022-07-09T07:47:04.098 nodeos    chain_plugin.cpp:462          operator()           ] Support for builtin protocol feature 'RAM_RESTRICTIONS' (with digest of '4e7bf348da00a945489b2a681749eb56f5de00b900014e137ddae39f48f69d67') is enabled with preactivation required
info  2022-07-09T07:47:04.098 nodeos    chain_plugin.cpp:571          operator()           ] Saved default specification for builtin protocol feature 'RAM_RESTRICTIONS' (with digest of '4e7bf348da00a945489b2a681749eb56f5de00b900014e137ddae39f48f69d67') to: /app/nodes/ralf/protocol_features/BUILTIN-RAM_RESTRICTIONS.json
info  2022-07-09T07:47:04.099 nodeos    chain_plugin.cpp:462          operator()           ] Support for builtin protocol feature 'GET_SENDER' (with digest of 'f0af56d2c5a48d60a4a5b5c903edfb7db3a736a94ed589d0b797df33ff9d3e1d') is enabled with preactivation required
info  2022-07-09T07:47:04.099 nodeos    chain_plugin.cpp:571          operator()           ] Saved default specification for builtin protocol feature 'GET_SENDER' (with digest of 'f0af56d2c5a48d60a4a5b5c903edfb7db3a736a94ed589d0b797df33ff9d3e1d') to: /app/nodes/ralf/protocol_features/BUILTIN-GET_SENDER.json
info  2022-07-09T07:47:04.099 nodeos    chain_plugin.cpp:462          operator()           ] Support for builtin protocol feature 'FORWARD_SETCODE' (with digest of '2652f5f96006294109b3dd0bbde63693f55324af452b799ee137a81a905eed25') is enabled with preactivation required
info  2022-07-09T07:47:04.099 nodeos    chain_plugin.cpp:571          operator()           ] Saved default specification for builtin protocol feature 'FORWARD_SETCODE' (with digest of '2652f5f96006294109b3dd0bbde63693f55324af452b799ee137a81a905eed25') to: /app/nodes/ralf/protocol_features/BUILTIN-FORWARD_SETCODE.json
info  2022-07-09T07:47:04.099 nodeos    chain_plugin.cpp:462          operator()           ] Support for builtin protocol feature 'ONLY_BILL_FIRST_AUTHORIZER' (with digest of '8ba52fe7a3956c5cd3a656a3174b931d3bb2abb45578befc59f283ecd816a405') is enabled with preactivation required
info  2022-07-09T07:47:04.099 nodeos    chain_plugin.cpp:571          operator()           ] Saved default specification for builtin protocol feature 'ONLY_BILL_FIRST_AUTHORIZER' (with digest of '8ba52fe7a3956c5cd3a656a3174b931d3bb2abb45578befc59f283ecd816a405') to: /app/nodes/ralf/protocol_features/BUILTIN-ONLY_BILL_FIRST_AUTHORIZER.json
info  2022-07-09T07:47:04.100 nodeos    chain_plugin.cpp:462          operator()           ] Support for builtin protocol feature 'RESTRICT_ACTION_TO_SELF' (with digest of 'ad9e3d8f650687709fd68f4b90b41f7d825a365b02c23a636cef88ac2ac00c43') is enabled with preactivation required
info  2022-07-09T07:47:04.100 nodeos    chain_plugin.cpp:571          operator()           ] Saved default specification for builtin protocol feature 'RESTRICT_ACTION_TO_SELF' (with digest of 'ad9e3d8f650687709fd68f4b90b41f7d825a365b02c23a636cef88ac2ac00c43') to: /app/nodes/ralf/protocol_features/BUILTIN-RESTRICT_ACTION_TO_SELF.json
info  2022-07-09T07:47:04.100 nodeos    chain_plugin.cpp:462          operator()           ] Support for builtin protocol feature 'DISALLOW_EMPTY_PRODUCER_SCHEDULE' (with digest of '68dcaa34c0517d19666e6b33add67351d8c5f69e999ca1e37931bc410a297428') is enabled with preactivation required
info  2022-07-09T07:47:04.100 nodeos    chain_plugin.cpp:571          operator()           ] Saved default specification for builtin protocol feature 'DISALLOW_EMPTY_PRODUCER_SCHEDULE' (with digest of '68dcaa34c0517d19666e6b33add67351d8c5f69e999ca1e37931bc410a297428') to: /app/nodes/ralf/protocol_features/BUILTIN-DISALLOW_EMPTY_PRODUCER_SCHEDULE.json
info  2022-07-09T07:47:04.100 nodeos    chain_plugin.cpp:462          operator()           ] Support for builtin protocol feature 'FIX_LINKAUTH_RESTRICTION' (with digest of 'e0fb64b1085cc5538970158d05a009c24e276fb94e1a0bf6a528b48fbc4ff526') is enabled with preactivation required
info  2022-07-09T07:47:04.101 nodeos    chain_plugin.cpp:571          operator()           ] Saved default specification for builtin protocol feature 'FIX_LINKAUTH_RESTRICTION' (with digest of 'e0fb64b1085cc5538970158d05a009c24e276fb94e1a0bf6a528b48fbc4ff526') to: /app/nodes/ralf/protocol_features/BUILTIN-FIX_LINKAUTH_RESTRICTION.json
info  2022-07-09T07:47:04.101 nodeos    chain_plugin.cpp:462          operator()           ] Support for builtin protocol feature 'REPLACE_DEFERRED' (with digest of 'ef43112c6543b88db2283a2e077278c315ae2c84719a8b25f25cc88565fbea99') is enabled with preactivation required
info  2022-07-09T07:47:04.101 nodeos    chain_plugin.cpp:571          operator()           ] Saved default specification for builtin protocol feature 'REPLACE_DEFERRED' (with digest of 'ef43112c6543b88db2283a2e077278c315ae2c84719a8b25f25cc88565fbea99') to: /app/nodes/ralf/protocol_features/BUILTIN-REPLACE_DEFERRED.json
info  2022-07-09T07:47:04.101 nodeos    chain_plugin.cpp:462          operator()           ] Support for builtin protocol feature 'NO_DUPLICATE_DEFERRED_ID' (with digest of '4a90c00d55454dc5b059055ca213579c6ea856967712a56017487886a4d4cc0f') is enabled with preactivation required
info  2022-07-09T07:47:04.102 nodeos    chain_plugin.cpp:571          operator()           ] Saved default specification for builtin protocol feature 'NO_DUPLICATE_DEFERRED_ID' (with digest of '4a90c00d55454dc5b059055ca213579c6ea856967712a56017487886a4d4cc0f') to: /app/nodes/ralf/protocol_features/BUILTIN-NO_DUPLICATE_DEFERRED_ID.json
info  2022-07-09T07:47:04.102 nodeos    chain_plugin.cpp:462          operator()           ] Support for builtin protocol feature 'ONLY_LINK_TO_EXISTING_PERMISSION' (with digest of '1a99a59d87e06e09ec5b028a9cbb7749b4a5ad8819004365d02dc4379a8b7241') is enabled with preactivation required
info  2022-07-09T07:47:04.102 nodeos    chain_plugin.cpp:571          operator()           ] Saved default specification for builtin protocol feature 'ONLY_LINK_TO_EXISTING_PERMISSION' (with digest of '1a99a59d87e06e09ec5b028a9cbb7749b4a5ad8819004365d02dc4379a8b7241') to: /app/nodes/ralf/protocol_features/BUILTIN-ONLY_LINK_TO_EXISTING_PERMISSION.json
info  2022-07-09T07:47:04.102 nodeos    chain_plugin.cpp:475          operator()           ] Support for builtin protocol feature 'PREACTIVATE_FEATURE' (with digest of '0ec7e080177b2c02b278d5088611686b49d739925a92d9bfcacd7fc6b74053bd') is enabled without activation restrictions
info  2022-07-09T07:47:04.103 nodeos    chain_plugin.cpp:571          operator()           ] Saved default specification for builtin protocol feature 'PREACTIVATE_FEATURE' (with digest of '0ec7e080177b2c02b278d5088611686b49d739925a92d9bfcacd7fc6b74053bd') to: /app/nodes/ralf/protocol_features/BUILTIN-PREACTIVATE_FEATURE.json
info  2022-07-09T07:47:04.104 nodeos    chain_plugin.cpp:1043         plugin_initialize    ] Starting fresh blockchain state using default genesis state.
warn  2022-07-09T07:47:04.108 nodeos    chain_plugin.cpp:1238         plugin_initialize    ] 3070000 wasm_exception: WASM Exception
eos_vm_jit wasm runtime not supported on this platform and/or configuration
    {"r":"eos_vm_jit"}
    nodeos  wasm_interface_private.hpp:79 wasm_interface_impl

Failed to initialize

**Comment by ericpassmore** [comment]
Suggestion for DUNE after changing the config.ini to reference `eos_vm`, destroy the container and rerun bootstrap. This resolved issue #8 , they reported the same issue. 

I know I had problems with the docker volume mount.

**Comment by larryk85** [comment]
> Suggestion for DUNE after changing the config.ini to reference `eos_vm`, destroy the container and rerun bootstrap. This resolved issue #8 , they reported the same issue.
> 
> I know I had problems with the docker volume mount.

Indeed, we've actually already fixed this particular issue and a few others in a different branch that is being primed for the v1.0-rc1 release of DUNE (currently looking like we are going to be releasing that end of week this week or beginning of week next week).

There will be a section in the README and the release notes of how to upgrade from prerelease to v1.0-rc1.

Thank you for bringing this up.

**Comment by ericpassmore** [comment]
Excellent looking forward to the new release

**Comment by RalfWeinand** [comment]
Awesome, thanks for the update. I'm happy to wait for the next release and test it again. I will keep an eye on it.

**Comment by larryk85** [comment]
This should be resolved as of v1.0.0-rc1
